from npu_patch.idefics2_conv_monkey_patch import replace_with_torch_npu_idefics2_visionembeddings
from npu_patch.idefics2_flash_attn_monkey_patch import replace_with_torch_npu_idefics2_flash_attention
from npu_patch.llama_rmsnorm_monkey_patch import replace_with_torch_npu_llama_rmsnorm
from npu_patch.llama_rope_monkey_patch import replace_with_torch_npu_llama_rope
from npu_patch.llama_flash_attn_monkey_patch import replace_with_torch_npu_llama_flash_attention
from npu_patch.transformers_check_flash_attn_monkey_patch import replace_with_torch_npu_check_flash_attn_2


replace_with_torch_npu_idefics2_visionembeddings()
replace_with_torch_npu_idefics2_flash_attention()
replace_with_torch_npu_llama_rmsnorm()
replace_with_torch_npu_llama_rope()
replace_with_torch_npu_llama_flash_attention()
replace_with_torch_npu_check_flash_attn_2()
